# Generated by Django 5.0 on 2023-12-23 13:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("user", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ToDo",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("contents", models.CharField(max_length=200)),
                ("due_datetime", models.DateTimeField(null=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="todos", to="user.user"
                    ),
                ),
            ],
            options={
                "db_table": "todo",
            },
        ),
    ]
